name: "build-dist"
on: # rebuild any branch changes
  push:
    paths:
      - '*'
      - '**/*'
      - '!dist/**'
    branches-ignore:
      - '*'
    tags-ignore:
      - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.17'
      - run: go build -v -o dist/main
      - uses: actions/upload-artifact@v4.4.0
        with:
          name: main-${{ matrix.runs-on }}
          path: dist/main
  publish:
    name: Publish new action version
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4.1.8
        with:
          path: main-ubuntu-latest/
          name: main-ubuntu-latest
      - uses: actions/download-artifact@v4.1.8
        with:
          path: main-macos-latest/
          name: main-macos-latest
      - uses: actions/download-artifact@v4.1.8
        with:
          path: main-windows-latest/
          name: main-windows-latest
      - name: Rename binaries
        run: |
          mkdir -p dist
          mv main-ubuntu-latest/main dist/main_linux
          mv main-macos-latest/main dist/main_darwin
          mv main-windows-latest/main dist/main_windows.exe
          chmod a+x dist/main_*
      - name: Commit and push
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add dist/main_*
          git commit -m "Built new distributable packages"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
