name: "unit-test"
on: # rebuild any branch changes
  push:

jobs:
  unit-test:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.22'
      - run: go test -v ./...
